site_name = "Wordfeudligan"
site_description = "Wordfeudligan går av stapeln en gång per termin. På de här sajten finns automatiskt uträknade ratingvärden för alla spelare som är eller har varit med i ligan."
